name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - 'main'
      - 'deploy-to-cloud-run'

env:
  PROJECT_ID: '${{ vars.GCP_PROJECT_ID }}'
  REGION: '${{ vars.REGION }}'
  SERVICE: '${{ vars.SERVICE_NAME }}'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          source: './'
          env_vars: |-
            DB_URL=${{ secrets.DB_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}

      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
